id=js
name=JavaScript (New)
version=${project.version}
description=${project.description}
class=io.gravitee.policy.js.JsPolicy
type=policy
category=others
documentation=POLICY_STUDIO_DOC.md
schema=schema-form.json
proxy=REQUEST,RESPONSE
message=REQUEST,RESPONSE,MESSAGE_REQUEST,MESSAGE_RESPONSE
